-- Lume — dados iniciais do servidor (gerado de assets/seed/*.json). Rode depois do schema.sql.

insert into public.lista_valor (lista, codigo, rotulo, ordem) values
  ('forma_vida', 'arvore', 'Árvore', 0),
  ('forma_vida', 'arbusto', 'Arbusto', 1),
  ('forma_vida', 'palmeira', 'Palmeira', 2),
  ('forma_vida', 'graminea', 'Gramínea/capim', 3),
  ('forma_vida', 'trepadeira', 'Trepadeira', 4),
  ('forma_vida', 'herbacea', 'Herbácea', 5),
  ('forma_vida', 'outra', 'Outra', 6),
  ('estagio', 'plantula', 'Plântula', 0),
  ('estagio', 'jovem', 'Jovem', 1),
  ('estagio', 'adulto', 'Adulto', 2),
  ('estagio', 'reprodutivo', 'Adulto com flor/fruto', 3),
  ('estagio', 'misto', 'Vários estágios', 4),
  ('estagio', 'nao_informado', 'Não informado', 5),
  ('quantificacao_tipo', 'contagem', 'Nº de indivíduos', 0),
  ('quantificacao_tipo', 'classe', 'Classe de abundância', 1),
  ('quantificacao_tipo', 'area', 'Área ocupada (m²)', 2),
  ('quantificacao_tipo', 'cobertura', 'Cobertura (%)', 3),
  ('classe_abundancia', 'c1', '1 indivíduo', 0),
  ('classe_abundancia', 'c2', '2–5', 1),
  ('classe_abundancia', 'c3', '6–20', 2),
  ('classe_abundancia', 'c4', '21–100', 3),
  ('classe_abundancia', 'c5', 'Mais de 100 / mancha extensa', 4),
  ('ambiente', 'interior_mata', 'Interior da mata', 0),
  ('ambiente', 'borda', 'Borda da mata', 1),
  ('ambiente', 'clareira', 'Clareira', 2),
  ('ambiente', 'beira_trilha', 'Beira de trilha', 3),
  ('ambiente', 'beira_estrada', 'Beira de estrada', 4),
  ('ambiente', 'area_aberta', 'Área aberta/pasto', 5),
  ('ambiente', 'margem_rio', 'Margem de rio/córrego', 6),
  ('ambiente', 'talhao', 'Talhão plantado', 7),
  ('ambiente', 'outro', 'Outro', 8),
  ('status_foco', 'detectado', 'Detectado', 0),
  ('status_foco', 'em_controle', 'Em controle', 1),
  ('status_foco', 'controlado', 'Controlado', 2),
  ('status_foco', 'rebrotou', 'Rebrotou', 3),
  ('status_foco', 'erradicado', 'Erradicado', 4),
  ('status_foco', 'descartado', 'Descartado', 5),
  ('metodo_manejo', 'arranquio', 'Arranquio manual', 0),
  ('metodo_manejo', 'rocada', 'Roçada/capina', 1),
  ('metodo_manejo', 'corte_raso', 'Corte rente à base', 2),
  ('metodo_manejo', 'anelamento', 'Anelamento', 3),
  ('metodo_manejo', 'corte_herbicida', 'Corte + herbicida no toco', 4),
  ('metodo_manejo', 'anelamento_herbicida', 'Anelamento + herbicida', 5),
  ('metodo_manejo', 'herbicida_foliar', 'Herbicida foliar', 6),
  ('metodo_manejo', 'remocao_frutos', 'Remoção de frutos/sementes', 7),
  ('metodo_manejo', 'outro', 'Outro', 8),
  ('destinacao', 'deixado_secar', 'Deixado no local para secar', 0),
  ('destinacao', 'amontoado', 'Amontoado no local', 1),
  ('destinacao', 'removido', 'Removido da área', 2),
  ('destinacao', 'ensacado', 'Ensacado', 3),
  ('destinacao', 'outro', 'Outro', 4),
  ('resultado_revisita', 'ausente', 'Ausente', 0),
  ('resultado_revisita', 'presente_reduzido', 'Presente, reduzido', 1),
  ('resultado_revisita', 'presente_igual', 'Presente, sem mudança', 2),
  ('resultado_revisita', 'presente_aumentou', 'Presente, aumentou', 3),
  ('resultado_revisita', 'rebrota', 'Rebrota em indivíduos tratados', 4),
  ('origem_coordenada', 'gps_auto', 'GPS automático', 0),
  ('origem_coordenada', 'gps_ajustado', 'Ajustado no mapa', 1),
  ('origem_coordenada', 'estimada', 'Estimada', 2),
  ('condicao_tempo', 'seco', 'Seco', 0),
  ('condicao_tempo', 'nublado', 'Nublado', 1),
  ('condicao_tempo', 'chuva', 'Chuva', 2)
on conflict (lista, codigo) do update set rotulo = excluded.rotulo, ordem = excluded.ordem;

insert into public.especies (id, prefixo, nome_cientifico, nomes_populares, familia, forma_vida, descricao_identificacao, confusao_com, controle_citado, metodos_sugeridos, ordem) values
  ('acacia_mangium', 'ACA', 'Acacia mangium Willd.', array['acácia-mangium','acácia']::text[], 'Fabaceae', 'arvore', 'Árvore de crescimento rápido. As "folhas" são simples e largas, com 3 a 4 nervuras paralelas no comprimento (filódios). Flores em espigas amarelo-claras. Vagens enroladas.', null, 'Corte na base com motosserra + herbicida triclopir.', array['corte_herbicida']::text[], 1),
  ('artocarpus_heterophyllus', 'JAQ', 'Artocarpus heterophyllus Lam.', array['jaqueira']::text[], 'Moraceae', 'arvore', 'Árvore grande, com látex branco. Folhas simples, grossas e brilhantes. Frutos enormes presos ao tronco e aos galhos grossos.', 'O fruto atrai a fauna, que espalha as sementes.', 'Anelamento + triclopir.', array['anelamento_herbicida']::text[], 2),
  ('clitoria_fairchildiana', 'SOM', 'Clitoria fairchildiana R.A. Howard', array['sombreiro']::text[], 'Fabaceae', 'arvore', 'Folhas com 3 folíolos grandes. Flores lilás a roxas. Vagens longas.', null, null, '{}'::text[], 3),
  ('euterpe_oleracea', 'ACI', 'Euterpe oleracea Mart.', array['açaí']::text[], 'Arecaceae', 'palmeira', 'Palmeira em touceira (vários caules juntos).', 'Não confundir com a juçara (Euterpe edulis), nativa e ameaçada, que tem caule único.', null, '{}'::text[], 4),
  ('leucaena_leucocephala', 'LEU', 'Leucaena leucocephala (Lam.) de Wit', array['leucena']::text[], 'Fabaceae', 'arbusto', 'Folhas recortadas em muitos folíolos pequenos. Flores brancas em "pompom". Vagens achatadas em cachos.', null, null, '{}'::text[], 5),
  ('mimosa_caesalpiniifolia', 'SAB', 'Mimosa caesalpiniifolia Benth.', array['sabiá','sansão-do-campo']::text[], 'Fabaceae', 'arvore', 'Árvore com espinhos e folhas recortadas. Flores brancas em espigas. Comum em cercas vivas.', 'Nativa do Nordeste, exótica aqui.', null, '{}'::text[], 6),
  ('muntingia_calabura', 'CAL', 'Muntingia calabura L.', array['calabura']::text[], 'Muntingiaceae', 'arvore', 'Árvore pequena. Folhas assimétricas, peludas e pegajosas. Flor branca. Frutinhos vermelhos e doces.', 'Os frutos são muito procurados por aves, que dispersam as sementes.', 'Corte (árvore isolada) ou anelamento (dentro da mata) + herbicida.', array['corte_herbicida','anelamento_herbicida']::text[], 7),
  ('megathyrsus_maximus', 'COL', 'Megathyrsus maximus (Jacq.) B.K.Simon & S.W.L.Jacobs', array['capim-colonião']::text[], 'Poaceae', 'graminea', 'Capim alto em touceiras (pode passar de 2 m). Inflorescência aberta e ramificada. Domina clareiras e bordas.', 'Aumenta o risco de fogo.', null, '{}'::text[], 8),
  ('thunbergia_alata', 'AMA', 'Thunbergia alata Bojer ex Sims', array['amarelinha','olho-de-poeta']::text[], 'Acanthaceae', 'trepadeira', 'Trepadeira. Flores amarelo-alaranjadas com o centro escuro ("olho"). Folhas em forma de ponta de flecha.', 'Cobre outras plantas.', null, '{}'::text[], 9),
  ('tradescantia_zebrina', 'LAM', 'Tradescantia zebrina Bosse', array['lambari-roxo','trapoeraba-roxa']::text[], 'Commelinaceae', 'herbacea', 'Rasteira. Folhas listradas de verde-prateado em cima e roxas embaixo. Forma tapetes no chão da mata.', 'Rebrota de qualquer pedaço: retirar a planta inteira.', 'Arranquio manual cuidadoso (sem deixar fragmentos) + secagem ao sol.', array['arranquio']::text[], 10),
  ('outra', 'OUT', 'Outra espécie / não identificada', array['Outra espécie / não sei']::text[], null, 'outra', 'Use quando a planta não estiver no catálogo ou houver dúvida. Foto e descrição são obrigatórias. Pode ser uma espécie nova na Flona (detecção precoce).', 'Eucalipto em talhão plantado não é foco de invasão. Registre só regeneração fora do talhão.', null, '{}'::text[], 99)
on conflict (id) do nothing;
